import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";
import AudioPlayer from "@/components/AudioPlayer";
import Centre from "@/components/CenterLogoPage";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Centre />
        <AudioPlayer />
        <Header />
          {children}
      </body>
    </html>
  );
}
